// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Status  int         `json:"status"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type RedisGet struct {
	Name string `json:"name,optional"`
}

type RedisGet2 struct {
	Name string `form:"name,optional"`
}

type RedisSet struct {
	Key   string `form:"key,optional"`
	Value string `form:"value,optional"`
}
