// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	mysql "demo/gozero115/internal/handler/mysql"
	redis "demo/gozero115/internal/handler/redis"
	user "demo/gozero115/internal/handler/user"
	"demo/gozero115/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: IndexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: user.IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/get",
				Handler: redis.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get2",
				Handler: redis.GettwoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/set",
				Handler: redis.SetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/redis"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: mysql.IndexHandler(serverCtx),
			},
		},
		rest.WithPrefix("/mysql"),
	)
}
